### ISSUE TITLE
AttributeError: module 'socket' has no attribute 'TCP_KEEPIDLE'

### ISSUE THREAD

**Issue by scsidisk** [faicker/greendns#1]
Mac OS 10.14.3
$ greendns -r greendns
[2019-03-29 14:00:10,691][INFO]: received request, name=www.google.com., type=A, id=8481
Traceback (most recent call last):
  File "/usr/local/bin/greendns", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/greendns/server.py", line 150, in main
    run(sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/greendns/server.py", line 146, in run
    dns.run_forwarder()
  File "/usr/local/lib/python3.7/site-packages/greendns/server.py", line 138, in run_forwarder
    self.forwarder.run_forever()
  File "/usr/local/lib/python3.7/site-packages/greendns/forwarder.py", line 146, in run_forever
    self.server.run()
  File "/usr/local/lib/python3.7/site-packages/greendns/connection.py", line 46, in run
    self.io_engine.run()
  File "/usr/local/lib/python3.7/site-packages/greendns/ioloop.py", line 89, in run
    callback(sock, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/greendns/connection.py", line 134, in __handle_arecv
    on_recved(self, remote_addr, data, cerr, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/greendns/forwarder.py", line 79, in handle_request_from_client
    conn.aconnect(remote_addr, self.handle_tcp_connected)
  File "/usr/local/lib/python3.7/site-packages/greendns/connection.py", line 201, in aconnect
    self.set_keepalive()
  File "/usr/local/lib/python3.7/site-packages/greendns/connection.py", line 146, in set_keepalive
    self.sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPIDLE, 2)
AttributeError: module 'socket' has no attribute 'TCP_KEEPIDLE'

**Comment by faicker** [comment]
This is because TCP_KEEPIDLE constant does not exist on MacOS.
It will be fixed soon.

**Comment by scsidisk** [comment]
I see.

**Comment by faicker** [comment]
Fixed in release 0.9.10.
